import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const outfitSans = Outfit({
	variable: "--font-main-sans",
	subsets: ["latin"],
});

const nyghtSerif = localFont({
	src: [
		{
			path: "../../public/font/NyghtSerif-Medium.woff2",
			weight: "500",
			style: "medium",
		},
		{
			path: "../../public/font/NyghtSerif-Medium.woff",
			weight: "500",
			style: "medium",
		},
	],
	display: "swap",
	variable: "--font-nyght-serif",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${outfitSans.variable} ${nyghtSerif.variable} font-main antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
